version: 2.1
jobs:
  test:
    docker:
      - image: circleci/node:10.16.3
    steps:
      - checkout
      - run: npm install
      - run: npm test
      - run: npm run test:load
workflows:
  version: 2
  node-tests:
    jobs:
      - test